production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/kiji_prod
    solr_home: solr
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/kiji_development
    solr_home: solr

#test:
#  solr:
#    hostname: localhost
#    port: 8981
#    log_level: WARNING
#    solr_home: solr
#    path: /solr/kiji_test   
